# Generated by Django 6.1.1 on 2026-10-08 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBSObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(help_text='Name of the employee submitting the BBS observation.', max_length=150)),
                ('card_no', models.CharField(db_index=True, help_text='Employee card number.', max_length=30)),
                ('observation_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('observation_time', models.TimeField(default=django.utils.timezone.localtime)),
                ('shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], db_index=True, max_length=1)),
                ('area', models.CharField(max_length=150)),
                ('observer_name', models.CharField(blank=True, help_text='Optional observer name.', max_length=150)),
                ('activator', models.TextField(blank=True, help_text='What prompted the behaviour, such as sign, instruction, condition or habit.')),
                ('behaviour_type', models.CharField(choices=[('SAFE', 'Safe Act'), ('AT_RISK', 'At-Risk Act')], db_index=True, max_length=20)),
                ('behaviour_categories', models.JSONField(blank=True, default=list, help_text='Selected behaviour categories such as PPE, LOTO, Ergonomics, Tools, Housekeeping or Permit.')),
                ('behaviour_description', models.TextField(blank=True)),
                ('consequences', models.JSONField(blank=True, default=list, help_text='Selected consequences or feedback actions.')),
                ('feedback', models.TextField(blank=True, help_text='Feedback given on the spot.')),
                ('ppe_status', models.CharField(choices=[('SAFE', 'Safe'), ('AT_RISK', 'At-Risk'), ('NA', 'N/A')], max_length=20, verbose_name='PPE Compliance')),
                ('guarding_loto_status', models.CharField(choices=[('SAFE', 'Safe'), ('AT_RISK', 'At-Risk'), ('NA', 'N/A')], max_length=20, verbose_name='Machine Guarding / LOTO')),
                ('ergonomics_status', models.CharField(choices=[('SAFE', 'Safe'), ('AT_RISK', 'At-Risk'), ('NA', 'N/A')], max_length=20, verbose_name='Body Position / Ergonomics')),
                ('tools_equipment_status', models.CharField(choices=[('SAFE', 'Safe'), ('AT_RISK', 'At-Risk'), ('NA', 'N/A')], max_length=20, verbose_name='Tools / Equipment')),
                ('housekeeping_status', models.CharField(choices=[('SAFE', 'Safe'), ('AT_RISK', 'At-Risk'), ('NA', 'N/A')], max_length=20, verbose_name='Housekeeping')),
                ('permit_procedure_status', models.CharField(choices=[('SAFE', 'Safe'), ('AT_RISK', 'At-Risk'), ('NA', 'N/A')], max_length=20, verbose_name='Permit / Procedure')),
                ('root_causes', models.JSONField(blank=True, default=list, help_text='Likely root causes selected when at-risk behaviour is observed.')),
                ('root_cause_other', models.CharField(blank=True, max_length=250)),
                ('corrective_action', models.TextField(blank=True, help_text='Corrective or preventive action identified during the observation.')),
                ('observer_sign', models.CharField(blank=True, max_length=150)),
                ('supervisor_sign', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BBS Observation',
                'verbose_name_plural': 'BBS Observations',
                'ordering': ['-observation_date', '-submitted_at'],
                'indexes': [models.Index(fields=['observation_date', 'card_no'], name='bbs_date_card_idx'), models.Index(fields=['observation_date', 'shift'], name='bbs_date_shift_idx'), models.Index(fields=['behaviour_type', 'observation_date'], name='bbs_behavior_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('card_no', 'observation_date'), name='unique_daily_bbs_card_submission')],
            },
        ),
    ]
