# """
# Django settings for config project.

# Generated by 'django-admin startproject' using Django 6.1.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.1/ref/settings/
# """

# import os
# from pathlib import Path
# from django.contrib.messages import constants as messages
# from dotenv import load_dotenv



# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# load_dotenv(BASE_DIR / ".env")


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# # --- Core toggles, driven by environment ---
# # Locally: leave DJANGO_DEBUG unset (or "True") to get dev behavior.
# # In production: set DJANGO_DEBUG=False and provide the other env vars below.
# DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# # SECURITY WARNING: keep the secret key used in production secret!
# # The hardcoded value below is ONLY a fallback for local development.
# SECRET_KEY = os.environ.get(
#     "DJANGO_SECRET_KEY",
#     "django-insecure-xap@y_s9)-yxbcz0(c0wm+eyvtr0p4r%_po4*8=yfw0ny-+9tm",
# )

# if DEBUG:
#     ALLOWED_HOSTS = ["*"]
# else:
#     ALLOWED_HOSTS = os.environ.get(
#         "DJANGO_ALLOWED_HOSTS",
#         "127.0.0.1,localhost"
#     ).split(",")

# # ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
# if RENDER_EXTERNAL_HOSTNAME:
#     ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'dashboard',
#     'production',
#     'usermanagement',
#     'quality',
#     'safety',
#     'safety_bbs'
# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'config.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / "config" / "templates"],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'config.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }

# DATABASES = {
#     'default': {
#     'ENGINE': os.getenv('DB_ENGINE'),
#     'NAME': os.getenv('DB_NAME'),
#     'USER': os.getenv('DB_USER'),
#     'PASSWORD': os.getenv('DB_PASSWORD'),
#     'HOST': os.getenv('DB_HOST'),
#     'PORT': os.getenv('DB_PORT'),
#     }
# }

# # Password validation
# # https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.1/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.1/howto/static-files/

# STATIC_URL = 'static/'
# STATICFILES_DIRS = [BASE_DIR / "static",]
# STATIC_ROOT = BASE_DIR / "config" / "staticfiles"
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "config" / "media"


# # Email
# # https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# if DEBUG:
#     MAILERS = {
#         'default': {
#             'BACKEND': 'django.core.mail.backends.console.EmailBackend',
#         },
#     }
# else:
#     MAILERS = {
#         'default': {
#             'BACKEND': 'django.core.mail.backends.console.EmailBackend',
#         },
#     }
#     # MAILERS = {
#     #     'default': {
#     #         'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
#     #         'HOST': os.environ.get("EMAIL_HOST"),
#     #         'PORT': int(os.environ.get("EMAIL_PORT", 587)),
#     #         'USE_TLS': True,
#     #         'USER': os.environ.get("EMAIL_HOST_USER"),
#     #         'PASSWORD': os.environ.get("EMAIL_HOST_PASSWORD"),
#     #     },
#     # }


# # Security
# # https://docs.djangoproject.com/en/6.1/ref/settings/#security
# # These are only enforced when DEBUG=False, so local dev is unaffected.

# SECURE_SSL_REDIRECT = not DEBUG
# SESSION_COOKIE_SECURE = not DEBUG
# CSRF_COOKIE_SECURE = not DEBUG

# CSRF_TRUSTED_ORIGINS = [
#     "https://jkoms.sarvans.com",
# ]

# if not DEBUG:
#     # Start low (e.g. 3600 = 1 hour), raise once you've confirmed HTTPS
#     # works site-wide. A bad HSTS rollout can lock users out for as long
#     # as this value, so don't jump straight to 31536000 (1 year).
#     SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", 3600))
#     SECURE_HSTS_INCLUDE_SUBDOMAINS = True
#     SECURE_HSTS_PRELOAD = True

#     # Only needed if a reverse proxy (nginx, load balancer, etc.) terminates
#     # TLS and forwards requests to Django over plain HTTP.
#     SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# AUTH_USER_MODEL = "usermanagement.User"

# LOGIN_URL = "login"
# LOGIN_REDIRECT_URL = "home"
# LOGOUT_REDIRECT_URL = "login"

# MESSAGE_TAGS = {
#     messages.DEBUG: "secondary",
#     messages.INFO: "info",
#     messages.SUCCESS: "success",
#     messages.WARNING: "warning",
#     messages.ERROR: "danger",
# }

"""
Django settings for the LTPOMS project.
"""

import os
from pathlib import Path

from django.contrib.messages import constants as messages
from dotenv import load_dotenv


# =============================================================================
# PATHS / ENVIRONMENT
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(
    BASE_DIR / ".env"
)


def env_bool(
    name,
    default=False,
):
    """
    Read a boolean environment variable.

    Accepted true values:
        true
        1
        yes
        on
    """

    value = os.environ.get(
        name,
        str(default),
    )

    return value.strip().lower() in {
        "true",
        "1",
        "yes",
        "on",
    }


def env_list(
    name,
    default="",
):
    """
    Read a comma-separated environment variable
    and return a clean Python list.
    """

    value = os.environ.get(
        name,
        default,
    )

    return [
        item.strip()
        for item in value.split(",")
        if item.strip()
    ]


# =============================================================================
# CORE SECURITY
# =============================================================================

DEBUG = env_bool(
    "DJANGO_DEBUG",
    True,
)

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
)

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = (
            "django-insecure-local-development-only-"
            "replace-this-value"
        )
    else:
        raise RuntimeError(
            "DJANGO_SECRET_KEY must be configured "
            "when DJANGO_DEBUG=False."
        )


# =============================================================================
# HOSTS
# =============================================================================

ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "127.0.0.1,localhost",
)

RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME",
    "",
).strip()

if (
    RENDER_EXTERNAL_HOSTNAME
    and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS
):
    ALLOWED_HOSTS.append(
        RENDER_EXTERNAL_HOSTNAME
    )


# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # LTPOMS
    "dashboard",
    "production",
    "usermanagement",
    "quality",
    "safety",
    "safety_bbs",
]


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise should follow SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =============================================================================
# URL / WSGI
# =============================================================================

ROOT_URLCONF = "config.urls"

WSGI_APPLICATION = "config.wsgi.application"


# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django."
            "DjangoTemplates"
        ),

        "DIRS": [
            BASE_DIR / "config" / "templates",
        ],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth."
                    "context_processors.auth"
                ),
                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),
            ],
        },
    },
]


# =============================================================================
# DATABASE
# =============================================================================

DATABASES = {
    "default": {
        "ENGINE": os.environ.get(
            "DB_ENGINE",
            "django.db.backends.postgresql",
        ),

        "NAME": os.environ.get(
            "DB_NAME",
            "ltpoms",
        ),

        "USER": os.environ.get(
            "DB_USER",
            "postgres",
        ),

        "PASSWORD": os.environ.get(
            "DB_PASSWORD",
            "",
        ),

        "HOST": os.environ.get(
            "DB_HOST",
            "localhost",
        ),

        "PORT": os.environ.get(
            "DB_PORT",
            "5432",
        ),

        "CONN_MAX_AGE": int(
            os.environ.get(
                "DB_CONN_MAX_AGE",
                "60",
            )
        ),

        "CONN_HEALTH_CHECKS": True,
    },
}


# =============================================================================
# CUSTOM USER MODEL
# =============================================================================

AUTH_USER_MODEL = "usermanagement.User"


# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "en-us"

# Important for BBS daily submissions and dashboard date calculations.
TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = os.environ.get(
    "STATIC_URL",
    "/static/",
)

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = (
    BASE_DIR
    / "config"
    / "staticfiles"
)

STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage."
            "FileSystemStorage"
        ),
    },

    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


# =============================================================================
# MEDIA FILES
# =============================================================================

MEDIA_URL = os.environ.get(
    "MEDIA_URL",
    "/media/",
)

MEDIA_ROOT = (
    BASE_DIR
    / "config"
    / "media"
)


# =============================================================================
# EMAIL
# =============================================================================

EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.console."
        "EmailBackend"
    ),
)

EMAIL_HOST = os.environ.get(
    "EMAIL_HOST",
    "",
)

EMAIL_PORT = int(
    os.environ.get(
        "EMAIL_PORT",
        "587",
    )
)

EMAIL_USE_TLS = env_bool(
    "EMAIL_USE_TLS",
    True,
)

EMAIL_USE_SSL = env_bool(
    "EMAIL_USE_SSL",
    False,
)

EMAIL_HOST_USER = os.environ.get(
    "EMAIL_HOST_USER",
    "",
)

EMAIL_HOST_PASSWORD = os.environ.get(
    "EMAIL_HOST_PASSWORD",
    "",
)

DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL",
    EMAIL_HOST_USER or "webmaster@localhost",
)

SERVER_EMAIL = os.environ.get(
    "SERVER_EMAIL",
    DEFAULT_FROM_EMAIL,
)


# =============================================================================
# AUTHENTICATION REDIRECTS
# =============================================================================

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "home"

LOGOUT_REDIRECT_URL = "login"


# =============================================================================
# HTTPS / COOKIE SECURITY
# =============================================================================

USE_HTTPS = env_bool(
    "DJANGO_USE_HTTPS",
    False,
)

SECURE_SSL_REDIRECT = USE_HTTPS

SESSION_COOKIE_SECURE = USE_HTTPS

CSRF_COOKIE_SECURE = USE_HTTPS

SESSION_COOKIE_HTTPONLY = True

CSRF_COOKIE_HTTPONLY = False

SESSION_COOKIE_SAMESITE = "Lax"

CSRF_COOKIE_SAMESITE = "Lax"

X_FRAME_OPTIONS = "DENY"

SECURE_CONTENT_TYPE_NOSNIFF = True

SECURE_REFERRER_POLICY = (
    "strict-origin-when-cross-origin"
)


# =============================================================================
# CSRF TRUSTED ORIGINS
# =============================================================================

CSRF_TRUSTED_ORIGINS = env_list(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    (
        "http://194.9.10.175:8000,"
        "https://jkoms.sarvans.com"
    ),
)


# =============================================================================
# PROXY / HSTS
# =============================================================================

TRUST_PROXY_SSL = env_bool(
    "DJANGO_TRUST_PROXY_SSL",
    False,
)

if TRUST_PROXY_SSL:
    SECURE_PROXY_SSL_HEADER = (
        "HTTP_X_FORWARDED_PROTO",
        "https",
    )

if USE_HTTPS:
    SECURE_HSTS_SECONDS = int(
        os.environ.get(
            "DJANGO_HSTS_SECONDS",
            "3600",
        )
    )

    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
        "DJANGO_HSTS_INCLUDE_SUBDOMAINS",
        True,
    )

    SECURE_HSTS_PRELOAD = env_bool(
        "DJANGO_HSTS_PRELOAD",
        False,
    )
else:
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False


# =============================================================================
# MESSAGES
# =============================================================================

MESSAGE_TAGS = {
    messages.DEBUG: "secondary",
    messages.INFO: "info",
    messages.SUCCESS: "success",
    messages.WARNING: "warning",
    messages.ERROR: "danger",
}


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)